### convolution process

In [2]:
import tensorflow as tf
import numpy as np

## input source

In [7]:
x = np.array([[1,2,3,7],[6,3,4,2],[5,0,5,0],[4,1,8,4]])

## kernel

In [8]:
kernel_filter = np.array([[1,-1],[1,-1]])

## convolution process

In [13]:
tensor_x = tf.constant(x, tf.float32)
tensor_k = tf.constant(kernel_filter, tf.float32)

# be careful that convolution input must be both 4 dimensional
# definition of stride and padding:https://towardsdatascience.com/covolutional-neural-network-cb0883dd6529
# padding difference: 'SAME' or 'VALID', https://stackoverflow.com/questions/37674306/what-is-the-difference-between-same-and-valid-padding-in-tf-nn-max-pool-of-t
tensor_res = tf.nn.convolution(tf.reshape(tensor_x, [1, 4, 4, 1]), tf.reshape(tensor_k, [2, 2, 1, 1]), strides= 2, padding='VALID')

# sess = tf.Session()
# print(sess.run(tensor_res))
print(tensor_res)

tf.Tensor(
[[[[ 2.]
   [-2.]]

  [[ 8.]
   [ 9.]]]], shape=(1, 2, 2, 1), dtype=float32)


In [11]:
tensor_res+1

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 3.],
         [-1.]],

        [[ 9.],
         [10.]]]], dtype=float32)>

# another example

In [17]:
x = np.array([[1,2,3,7],[6,3,4,2]])
k = np.array([[-0.0308,-0.4722],[-0.3021,-0.0464]])
tensor_x = tf.constant(x,tf.float32)
tensor_k = tf.constant(k,tf.float32)
tensor_res = tf.nn.convolution(tf.reshape(tensor_x,[1,2,4,1]),
tf.reshape(tensor_k,[2,2,1,1]), strides=2, padding='VALID')
print(tensor_res)

tf.Tensor(
[[[[-2.927]
   [-4.699]]]], shape=(1, 1, 2, 1), dtype=float32)


In [18]:
tensor_res+-0.4298

<tf.Tensor: shape=(1, 1, 2, 1), dtype=float32, numpy=
array([[[[-3.3568],
         [-5.1288]]]], dtype=float32)>